### PR TITLE
Correcting the folder names

### PR DESCRIPTION
**Pull request by Gallimathias**
Names the physical folder names as it is in the sln to improve communication and collaboration.

### CODE REVIEW

**Comment by Mr-Markus** [comment]
I understand what you mean and it would be a goog idea, but take a look at the CI results because there are over 116 error messages :-(

**Comment by Gallimathias** [comment]
yea i see Appveyor dind't see the path changes :D

**Comment by Gallimathias** [comment]
now it should be fixed

**Comment by Gallimathias** [comment]
Master merged to resolve conflicts

**Comment by Gallimathias** [comment]
@Mr-Markus now you can merge :D

**Comment by Mr-Markus** [comment]
@Gallimathias OK I will merge it after merge PR #60 because think it is easier to resolve conflicts. If you think other way just say it :-)

PS: I am on vacation until Sunday and will do it after it

**Comment by Mr-Markus** [comment]
Hm, there are many conflicts now... I also took a look at it and have to say that a src folder seems to be a more "state-of-the-art" naming convention for source code folders.
So i would prefer to change the name in the sln file, instead of renaming folderstructure.

Do you think you can change this in this PR? Otherwise I would suggest to create a new feature branch from last master (or develop) branch and change it there

@nicolaiw jfyi

**Comment by Gallimathias** [comment]
Yes, the conflicts come from the fact that you always work directly on the branch. I merge them into my branch then they are solved. 

Git realizes that this is renames-

The "separation" comes because more and more web projects exist. In fact it is common for JavaScript and Co. to have a lowercase src folder.

But with C# the folder structure has a different convention. I see in many projects that adhere to a "web" structure difficulties in the communication of the collaborators. Not to mention all the tools which are based on the C# standard for C#.

Ultimately you can handle this like you want but I would find a C# standard for a C# project better as I would find a web standard for web projects better ^^

**Comment by Gallimathias** [comment]
P.s. if you want us to use src I can change that for you. Then it would be good to decide what comes under src and what doesn't. It would also be good to use rules to determine if you want to keep the folder structure under src.

**Comment by Mr-Markus** [comment]
I understand and it makes sense to me. I know that most JS projects have a src folder, but Microsoft in there [corefx](https://github.com/dotnet/corefx) repository, too. So I also named it src.

But i will merge it, because I could imagine to put libraries projects into this path and codegenerator into tools or anything like that. I don't know at the moment, but I will think about it in near future.

Thx :-)

**Comment by Gallimathias** [comment]
We can change that at any time if it is better for us otherwise.

I could imagine that we should separate the source code the topic documents in the repo overflow then it would be good to separate document and code more strictly for the sake of clarity

**Pull request merged**
